export const palette = {
  page: '#F6F4FB',
  surface: '#FFFFFF',
  surfaceSoft: '#FBFAFF',
  ink: '#161322',
  muted: '#726C83',
  faint: '#A7A0B7',
  line: '#E9E3F3',
  primary: '#7D44FE',
  primarySoft: '#EEE8FF',
  blue: '#5E83F6',
  blueSoft: '#EAF0FF',
  mint: '#50B5A6',
  mintSoft: '#E8F7F4',
  pink: '#FF6B8B',
  pinkSoft: '#FFECEF',
  amber: '#F4B740',
  amberSoft: '#FFF4D9',
  danger: '#EF5C6E',
  dangerSoft: '#FFECEF',
};

export const themeConfig = {
  token: {
    colorPrimary: palette.primary,
    colorSuccess: palette.mint,
    colorWarning: palette.amber,
    colorError: palette.danger,
    colorInfo: palette.blue,
    colorText: palette.ink,
    colorTextSecondary: palette.muted,
    colorTextTertiary: palette.faint,
    colorBgBase: palette.page,
    colorBgContainer: palette.surface,
    colorBorder: palette.line,
    colorBorderSecondary: '#F1ECF7',
    borderRadius: 8,
    borderRadiusLG: 10,
    boxShadow: '0 16px 40px rgba(78, 54, 132, 0.08)',
    fontFamily: `'Manrope', 'Nunito Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif`,
  },
  components: {
    Layout: {
      bodyBg: palette.page,
      headerBg: 'rgba(255,255,255,0.86)',
      siderBg: '#FBFAFF',
      triggerBg: palette.surface,
      triggerColor: palette.muted,
    },
    Menu: {
      itemBg: 'transparent',
      itemSelectedBg: palette.primarySoft,
      itemHoverBg: '#F4F0FF',
      itemColor: palette.muted,
      itemSelectedColor: palette.primary,
      itemBorderRadius: 8,
    },
    Card: {
      colorBgContainer: palette.surface,
      colorBorderSecondary: palette.line,
      borderRadiusLG: 10,
      paddingLG: 20,
    },
    Table: {
      colorBgContainer: palette.surface,
      colorText: palette.ink,
      colorTextHeading: palette.muted,
      borderColor: '#F0EAF7',
      headerBg: '#FBFAFF',
      rowHoverBg: '#F8F5FF',
      headerSplitColor: '#F0EAF7',
    },
    Button: {
      borderRadius: 8,
      primaryShadow: '0 10px 22px rgba(125, 68, 254, 0.22)',
      dangerShadow: '0 10px 22px rgba(239, 92, 110, 0.18)',
    },
    Input: {
      colorBgContainer: palette.surface,
      colorBorder: palette.line,
      colorText: palette.ink,
      colorTextPlaceholder: palette.faint,
      activeBorderColor: palette.primary,
      hoverBorderColor: '#CFC2F5',
    },
    Select: {
      colorBgContainer: palette.surface,
      colorBorder: palette.line,
      colorText: palette.ink,
    },
    Modal: {
      contentBg: palette.surface,
      headerBg: palette.surface,
      footerBg: palette.surface,
      titleColor: palette.ink,
    },
    Tag: {
      borderRadiusSM: 6,
    },
    Statistic: {
      contentFontSize: 30,
    },
  },
};
